name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "pnpm exec prisma generate"
dev = "pnpm exec prisma migrate deploy && pnpm exec react-router dev"