# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fcc74fe0b7cefebb6f344feddfc0233"
name = "AltText Magic"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "magic-ai-test-01.myshopify.com"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "bulk_operations/finish",
  "collections/create",
  "collections/delete",
  "collections/update",
  "products/create",
  "products/delete",
  "products/update"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_products,write_content,write_files,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
